apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.env }}
  namspace: {{ .Values.env}}
  labels:
    app: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
  spec:
    containers:
    - name: {{ .Values.appName }}
      image: pavansa/notes-app
      resources:
        requests:
          cpu: "100m"
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3000
