apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: {{ .Values.appName }}-{{  .Values.env}}
 namespace: {{ .Values.env}}
spec:
 selector:
   # Selector for Pods
   app: {{ .Values.appName }}
 ports:
   # Port Map
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer
