apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-app-deployment
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    - chart: webapp
    repoURL: https://github.com/cloudus123/apps-of-apps.git
    path: ./apps-of-apps/helm/
    targetRevision: 1.0.0
    ref: values
    helm:
      valueFiles:
      - $values/apps/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
	syncOptions:
	- CreateNamespace=true
